### ISSUE TITLE
Video Sprite not work on EK?

### ISSUE THREAD

**Issue by LunaEK** [FunkinExtraKeys/FNF-PsychEngine-EK#12]
### What is your question?

![Uploading image-1.png…](
![Uploading image-2.png...](

Some reason the video sprite not work on your ek engine 
So i have asked my friend work help me fix it 
Also this one is same with 0.6.3

**Comment by tposejank** [comment]
Version??
It should definitely work, I didn't edit anything from Psych Engine itself.

**Comment by tposejank** [comment]
Issue has been identified.
