### ISSUE TITLE
The cutscene lua script always crashes the game.

### ISSUE THREAD

**Issue by MILKIDOTMASTER** [FunkinExtraKeys/FNF-PsychEngine-EK#13]
### Describe your bug here.

so im working on my own mod and i wanted to use multi key for the last song for fun, then everytime i boot up in story mode (i have a cutscene) the game takes a minute then closes automatically and i cant find any crash prompt or nothing. now i did start this mod on normal psych and only recently thought of multi key just thought that might be valuable info. (btw the script didnt crash the game in the og psych)

### Command Prompt/Terminal logs (if existing)

```bash
dont exist
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i didnt edit anything.

**Comment by tposejank** [comment]
Issue identified
