### ISSUE TITLE
A ludicrous amount of lag spikes for seemingly no reason.

### ISSUE THREAD

**Issue by Tattleamelia** [FunkinExtraKeys/FNF-PsychEngine-EK#18]
### Describe your bug here.

Not sure if this exactly falls under a bug report- but for whatever reason the engine seems to give heavy lag spikes for no reason. I don't just mean a little blip that throws of your rhythm either, I'm talking full-on lag spikes that can cause you to miss entire sections of a song and die if you have practice mode disabled.
From my testing, this only seems to happen when you have 5K or more, however it may apply to 3K and below as well. All I know is that it doesn't occur on 4K.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, this is completely the base EK.

**Comment by tposejank** [comment]
Is there a video you could provide? This doesnt occur on my end

**Comment by Tattleamelia** [comment]
Interestingly, it seems to've stopped when I tried recording. I think what might've happened was that I'm playing Extra Keys through an External Harddrive, and I may have plugged it in poorly my first time playing.
Whatever the case may be, it seems to've stopped now, so it probably was a me thing. Apologies for the false report!

**Comment by Tattleamelia** [comment]
https://github.com/user-attachments/assets/04217ab5-85c1-44fe-a10c-3be106a03816

Never mind! It started happening again and I managed to catch footage of it this time. It seems like it may build up lag the longer the game is running for? Because earlier during this session I was having very little lag-, blink and you'll miss it, almost.
(Footage in question is from my own HoloFunk Port, which I put into EK to tinker around with. However, this can also happen on Vanilla songs.)

**Comment by tposejank** [comment]
holy moly that's a lagspike

**Comment by tposejank** [comment]
Is this issue still around, @Tattleamelia ?
